#Requires -Version 5.1
<#
.SYNOPSIS
    One-shot builder for the Windows x64 setup (installer) of MuseScore Studio / Persian Tuner.

.DESCRIPTION
    This script automates the whole pipeline that is described in:
        docs/local-windows-x64-setup.md          (Persian setup guide)
        docs/windows-build-troubleshooting.md    (known errors and their fixes)

    It runs, in order:
        1.  Elevation check (re-launches itself as Administrator when needed)
        2.  Prerequisite detection (VS 2022 + MSVC x64, CMake, Ninja, 7-Zip, Git,
            Git Bash, Qt 6 msvc2022_64, WiX v3) and environment setup
        3.  git submodule update --init --recursive
        4.  buildscripts\ci\windows\setup.bat            (downloads dependencies + Jack)
        5.  make_build_mode_env.sh / make_build_number.sh (build metadata)
        6.  buildscripts\ci\windows\build.bat            (RelWithDebInfo + install)
        7.  buildscripts\ci\windows\package.bat          (.msi / .paf.exe / .7z)
        8.  checksum.sh + a summary of the produced artifacts

    Known problems from the troubleshooting guide that are handled automatically:
        *  "WSL ERROR: execvpe(/bin/bash) failed"  -> Git Bash is located and put in
           front of the WSL bash stub in PATH.
        *  Missing build.artifacts\env\*.env files -> generated (or regenerated for
           -PackageOnly) before the .bat scripts read them.
        *  Missing/renamed uuidgen.exe in the Windows SDK (package.bat has a hard
           coded 10.0.26100.0 path) -> the real uuidgen.exe is auto-detected, and if
           none exists the GUID is generated by PowerShell instead. The original
           package.bat is never modified; a patched copy is used from %TEMP%.
        *  package.bat started before build.release exists -> detected up front with
           a clear message instead of the confusing CMake / "File not found - WIX".

.PARAMETER BuildMode
    devel | nightly | testing | stable.  stable/testing produce an .msi,
    devel/nightly produce a .7z.  Default: stable.

.PARAMETER BuildNumber
    Build number used in the version string. Default: generated from the UTC date
    (same rule as make_build_number.sh, max 9 digits so WiX can fit it in an Int32).

.PARAMETER Portable
    Build the PortableApps (.paf.exe) flavour instead of the classic installer.

.PARAMETER QtDir
    Qt installation to use, e.g. C:\Qt\6.10.2\msvc2022_64.
    Auto-detected from QT_DIR / QTDIR / C:\Qt\* when omitted.

.PARAMETER WixDir
    WiX Toolset v3 root, e.g. "C:\Program Files (x86)\WiX Toolset v3.11".
    Auto-detected from %WIX% / Program Files when omitted.

.PARAMETER UpgradeGuid
    CPACK_WIX_UPGRADE_GUID. Keep it stable across releases so new MSIs upgrade
    older installations instead of installing side by side.

.PARAMETER DockWidgetsV2
    ON/OFF, passed to build.bat as --dockwidgets_v2. Default: ON (same as CI).

.PARAMETER InstallPrereqs
    Install the missing command line tools with Chocolatey
    (git, cmake, ninja, 7zip, wixtoolset). Qt and Visual Studio are never
    installed automatically.

.PARAMETER SkipDeps
    Do not run setup.bat (use when C:\musescore_dependencies is already populated).

.PARAMETER SkipSubmodules
    Do not run "git submodule update --init --recursive".

.PARAMETER BuildOnly
    Stop after build.bat, do not create the installer.

.PARAMETER PackageOnly
    Only run the packaging step on an existing build.release / build.install.

.PARAMETER CheckOnly
    Only run the prerequisite check and print the resolved environment.

.PARAMETER Clean
    Delete build.release, build.install, build.artifacts, msvc.build, msvc.install
    before building.

.PARAMETER Yes
    Do not ask anything, assume "yes" for every confirmation.

.PARAMETER NoElevate
    Do not try to re-launch as Administrator (fail instead).

.EXAMPLE
    .\build_setup_x64.ps1
    Full stable x64 MSI build with auto-detected tools.

.EXAMPLE
    .\build_setup_x64.ps1 -BuildMode stable -BuildNumber 2026090501 -QtDir C:\Qt\6.10.2\msvc2022_64

.EXAMPLE
    .\build_setup_x64.ps1 -Portable
    Build the PortableApps .paf.exe package.

.EXAMPLE
    .\build_setup_x64.ps1 -CheckOnly
    Just verify that the machine is ready to build.

.EXAMPLE
    .\build_setup_x64.ps1 -PackageOnly
    Re-create the installer from an existing build (fast, minutes instead of hours).

.NOTES
    Run from an elevated PowerShell. If the execution policy blocks the script:
        powershell -NoProfile -ExecutionPolicy Bypass -File .\build_setup_x64.ps1
    A full first build takes 2-4+ hours and needs ~30-50 GB of free disk space.
#>

[CmdletBinding()]
param(
    [ValidateSet('devel', 'nightly', 'testing', 'stable')]
    [string] $BuildMode = 'stable',

    [string] $BuildNumber = '',

    [switch] $Portable,

    [string] $QtDir = '',

    [string] $WixDir = '',

    [string] $UpgradeGuid = '11111111-1111-1111-1111-111111111111',

    [ValidateSet('ON', 'OFF')]
    [string] $DockWidgetsV2 = 'ON',

    [switch] $InstallPrereqs,
    [switch] $SkipDeps,
    [switch] $SkipSubmodules,
    [switch] $BuildOnly,
    [switch] $PackageOnly,
    [switch] $CheckOnly,
    [switch] $Clean,
    [switch] $Yes,
    [switch] $NoElevate
)

$ErrorActionPreference = 'Stop'

# ============================================================================
#  Constants
# ============================================================================

$RepoRoot        = $PSScriptRoot
$ArtifactsDir    = Join-Path $RepoRoot 'build.artifacts'
$EnvDir          = Join-Path $ArtifactsDir 'env'
$BuildDir        = Join-Path $RepoRoot 'build.release'
$InstallDir      = Join-Path $RepoRoot 'build.install'
$DepsDir         = 'C:\musescore_dependencies'
$JackDir         = 'C:\Program Files (x86)\Jack'
$SetupBat        = 'buildscripts\ci\windows\setup.bat'
$BuildBat        = 'buildscripts\ci\windows\build.bat'
$PackageBat      = 'buildscripts\ci\windows\package.bat'
$MinFreeGb       = 40
$MinCMakeVersion = [version]'3.28'

$script:StepNo    = 0
$script:BashExe   = $null
$script:LastNativeExitCode = 0
$script:Warnings  = New-Object System.Collections.Generic.List[string]
$script:StartTime = Get-Date

# ============================================================================
#  Output helpers
# ============================================================================

function Write-Step {
    param([string] $Message)
    $script:StepNo++
    Write-Host ''
    Write-Host ('=' * 78) -ForegroundColor DarkCyan
    Write-Host ("  STEP {0}  {1}" -f $script:StepNo, $Message) -ForegroundColor Cyan
    Write-Host ('=' * 78) -ForegroundColor DarkCyan
}

function Write-Ok   { param([string] $m) Write-Host "  [ OK ] $m"   -ForegroundColor Green }
function Write-Info { param([string] $m) Write-Host "  [info] $m"   -ForegroundColor Gray }
function Write-Note { param([string] $m) Write-Host "  [note] $m"   -ForegroundColor DarkGray }

function Write-Warn {
    param([string] $m)
    Write-Host "  [warn] $m" -ForegroundColor Yellow
    $script:Warnings.Add($m) | Out-Null
}

function Write-Fail { param([string] $m) Write-Host "  [FAIL] $m" -ForegroundColor Red }

function Confirm-Continue {
    param([string] $Question)
    if ($Yes) { return $true }
    $answer = Read-Host "  $Question [y/N]"
    return ($answer -match '^(y|yes)$')
}

# ============================================================================
#  Process helpers
# ============================================================================

function Invoke-CmdScript {
    # NOTE: $CommandLine must not contain double quotes. Windows PowerShell escapes
    # embedded quotes with a backslash when it builds the native command line, and
    # cmd.exe does not understand that escaping. All paths used here are relative to
    # the repository root, so they never contain spaces.
    param(
        [Parameter(Mandatory = $true)][string] $CommandLine,
        [Parameter(Mandatory = $true)][string] $Title,
        [switch] $AllowFailure
    )
    if ($CommandLine.Contains('"')) {
        throw "Internal error: command line must not contain quotes: $CommandLine"
    }
    Write-Info "cmd> $CommandLine"
    $global:LASTEXITCODE = 0
    & cmd.exe /d /s /c $CommandLine
    $script:LastNativeExitCode = $LASTEXITCODE
    if ($script:LastNativeExitCode -ne 0 -and -not $AllowFailure) {
        throw "$Title failed with exit code $script:LastNativeExitCode`n       Command: $CommandLine"
    }
}

function Invoke-BashScript {
    param(
        [Parameter(Mandatory = $true)][string[]] $Arguments,
        [Parameter(Mandatory = $true)][string]   $Title,
        [switch] $AllowFailure
    )
    if (-not $script:BashExe) {
        throw "bash was not resolved. Install Git for Windows (Git Bash) and re-run."
    }
    Write-Info ("bash> {0}" -f ($Arguments -join ' '))
    $global:LASTEXITCODE = 0
    & $script:BashExe @Arguments
    $script:LastNativeExitCode = $LASTEXITCODE
    if ($script:LastNativeExitCode -ne 0 -and -not $AllowFailure) {
        throw "$Title failed with exit code $script:LastNativeExitCode"
    }
}

function Get-EnvFileValue {
    # Reads the first line of a build.artifacts\env\*.env file, tolerating
    # missing/empty files (returns $null instead of throwing).
    param([string] $Path)
    if (-not (Test-Path -LiteralPath $Path)) { return $null }
    $line = Get-Content -LiteralPath $Path -TotalCount 1 -ErrorAction SilentlyContinue |
            Select-Object -First 1
    if ($null -eq $line) { return $null }
    $line = ([string]$line).Trim()
    if (-not $line) { return $null }
    return $line
}

function Get-CommandPath {
    param([string] $Name)
    $cmd = Get-Command $Name -CommandType Application -ErrorAction SilentlyContinue |
           Select-Object -First 1
    if ($cmd) { return $cmd.Source }
    return $null
}

function Add-ToPathFront {
    param([string] $Directory)
    if (-not $Directory) { return }
    if (-not (Test-Path -LiteralPath $Directory)) { return }
    $current = $env:PATH -split ';' | Where-Object { $_ }
    if ($current -notcontains $Directory) {
        $env:PATH = "$Directory;$env:PATH"
    }
}

# ============================================================================
#  Elevation
# ============================================================================

function Test-Administrator {
    $identity  = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($identity)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Invoke-SelfElevation {
    param($BoundParameters)

    $exeName = if ($PSVersionTable.PSEdition -eq 'Core') { 'pwsh.exe' } else { 'powershell.exe' }

    $argList = @('-NoLogo', '-NoProfile', '-ExecutionPolicy', 'Bypass', '-NoExit',
                 '-File', ('"{0}"' -f $PSCommandPath))

    if ($BoundParameters) {
        foreach ($entry in $BoundParameters.GetEnumerator()) {
            if ($entry.Key -eq 'NoElevate') { continue }
            $value = $entry.Value
            if ($value -is [System.Management.Automation.SwitchParameter]) {
                if ($value.IsPresent) { $argList += ('-{0}' -f $entry.Key) }
            }
            elseif ($value -is [bool]) {
                if ($value) { $argList += ('-{0}' -f $entry.Key) }
            }
            else {
                $argList += ('-{0}' -f $entry.Key)
                $argList += ('"{0}"' -f $value)
            }
        }
    }

    Write-Host ''
    Write-Host '  This script needs Administrator rights (setup.bat writes to' -ForegroundColor Yellow
    Write-Host "  C:\musescore_dependencies and 'C:\Program Files (x86)\Jack')." -ForegroundColor Yellow
    Write-Host '  Re-launching in an elevated PowerShell window...' -ForegroundColor Yellow
    Write-Host ("  {0} {1}" -f $exeName, ($argList -join ' ')) -ForegroundColor DarkGray

    Start-Process -FilePath $exeName -Verb RunAs -ArgumentList $argList -WorkingDirectory $RepoRoot
}

# ============================================================================
#  Prerequisite detection
# ============================================================================

function Resolve-Bash {
    # The WSL stub at C:\Windows\System32\bash.exe is what produces
    # "WSL ERROR: execvpe(/bin/bash) failed" in the build logs, so Git Bash wins.
    $gitBashCandidates = @()

    $gitExe = Get-CommandPath 'git.exe'
    if ($gitExe) {
        $gitRoot = Split-Path -Parent (Split-Path -Parent $gitExe)   # ...\Git\cmd\git.exe -> ...\Git
        $gitBashCandidates += (Join-Path $gitRoot 'bin\bash.exe')
    }
    $gitBashCandidates += 'C:\Program Files\Git\bin\bash.exe'
    $gitBashCandidates += 'C:\Program Files (x86)\Git\bin\bash.exe'
    $gitBashCandidates += (Join-Path $env:LOCALAPPDATA 'Programs\Git\bin\bash.exe')

    foreach ($candidate in $gitBashCandidates) {
        if ($candidate -and (Test-Path -LiteralPath $candidate)) {
            $script:BashExe = (Resolve-Path -LiteralPath $candidate).Path
            Add-ToPathFront (Split-Path -Parent $script:BashExe)
            Write-Ok "Git Bash: $script:BashExe"
            return $true
        }
    }

    $anyBash = Get-CommandPath 'bash.exe'
    if ($anyBash) {
        if ($anyBash -like "$env:SystemRoot\System32\*") {
            Write-Warn "Only the WSL bash stub was found ($anyBash). The CI scripts expect Git Bash;"
            Write-Warn "if the build dies with 'WSL ERROR: execvpe(/bin/bash) failed', install Git for Windows."
        }
        $script:BashExe = $anyBash
        Write-Ok "bash: $anyBash"
        return $true
    }

    Write-Fail 'bash not found. Install Git for Windows (includes Git Bash):  choco install -y git'
    return $false
}

function Resolve-VisualStudio {
    $vswhere = Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio\Installer\vswhere.exe'
    if (-not (Test-Path -LiteralPath $vswhere)) {
        Write-Fail 'vswhere.exe not found -> Visual Studio 2022 (or Build Tools) is not installed.'
        Write-Note 'Install "Desktop development with C++" with MSVC v143 x64/x86 and a Windows 11 SDK.'
        return $false
    }

    $installPath = & $vswhere -latest -products '*' `
        -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
        -property installationPath 2>$null | Select-Object -First 1

    if (-not $installPath) {
        Write-Fail 'No Visual Studio installation with the MSVC x64 toolset was found.'
        Write-Note 'Add the workload "Desktop development with C++" (MSVC v143) in the VS Installer.'
        return $false
    }

    $vcvars = Join-Path $installPath 'VC\Auxiliary\Build\vcvars64.bat'
    if (-not (Test-Path -LiteralPath $vcvars)) {
        Write-Fail "vcvars64.bat not found in $installPath (ninja_build.bat needs it)."
        return $false
    }

    Write-Ok "Visual Studio: $installPath"
    return $true
}

function Resolve-Qt {
    $candidates = @()
    if ($QtDir)             { $candidates += $QtDir }
    if ($env:QT_DIR)        { $candidates += $env:QT_DIR }
    if ($env:QTDIR)         { $candidates += $env:QTDIR }
    if ($env:QT_ROOT_DIR)   { $candidates += $env:QT_ROOT_DIR }

    if (-not $candidates) {
        foreach ($root in @('C:\Qt', 'D:\Qt', (Join-Path $env:SystemDrive 'Qt'))) {
            if (-not (Test-Path -LiteralPath $root)) { continue }
            $found = Get-ChildItem -LiteralPath $root -Directory -ErrorAction SilentlyContinue |
                     Where-Object { $_.Name -match '^6\.\d+' } |
                     Sort-Object { try { [version]$_.Name } catch { [version]'0.0' } } -Descending
            foreach ($versionDir in $found) {
                foreach ($abi in @('msvc2022_64', 'msvc2019_64')) {
                    $p = Join-Path $versionDir.FullName $abi
                    if (Test-Path -LiteralPath $p) { $candidates += $p }
                }
            }
        }
    }

    $qtHome = $null
    foreach ($candidate in $candidates) {
        if ($candidate -and (Test-Path -LiteralPath (Join-Path $candidate 'bin\qmake.exe'))) {
            $qtHome = (Resolve-Path -LiteralPath $candidate).Path
            break
        }
    }

    if (-not $qtHome) {
        Write-Fail 'Qt 6 (msvc2022_64) not found.'
        Write-Note 'Install Qt 6.10.2 "MSVC 2022 64-bit" plus the modules qt5compat,'
        Write-Note 'qtnetworkauth, qtshadertools, qtwebsockets - or pass -QtDir <path>.'
        Write-Note 'aqtinstall:  aqt install-qt windows desktop 6.10.2 win64_msvc2022_64 -O C:\Qt -m qt5compat qtnetworkauth qtshadertools qtwebsockets'
        return $false
    }

    if (-not (Test-Path -LiteralPath (Join-Path $qtHome 'bin\windeployqt.exe'))) {
        Write-Warn "windeployqt.exe missing in $qtHome\bin - the install step will fail."
    }

    # Required Qt modules (the build fails late and cryptically when one is missing)
    $requiredModules = @{
        'Qt6Core5Compat'  = 'qt5compat'
        'Qt6NetworkAuth'  = 'qtnetworkauth'
        'Qt6ShaderTools'  = 'qtshadertools'
        'Qt6WebSockets'   = 'qtwebsockets'
    }
    foreach ($module in $requiredModules.Keys) {
        $cmakeDir = Join-Path $qtHome ('lib\cmake\{0}' -f $module)
        if (-not (Test-Path -LiteralPath $cmakeDir)) {
            Write-Warn ("Qt module '{0}' ({1}) seems to be missing in this Qt installation." -f $requiredModules[$module], $module)
        }
    }

    $env:QT_DIR      = $qtHome
    $env:QTDIR       = $qtHome
    $env:QT_ROOT_DIR = $qtHome
    $env:Qt6_DIR     = Join-Path $qtHome 'lib\cmake\Qt6'
    if ($env:CMAKE_PREFIX_PATH -and ($env:CMAKE_PREFIX_PATH -notlike "*$qtHome*")) {
        $env:CMAKE_PREFIX_PATH = "$qtHome;$env:CMAKE_PREFIX_PATH"
    }
    elseif (-not $env:CMAKE_PREFIX_PATH) {
        $env:CMAKE_PREFIX_PATH = $qtHome
    }
    Add-ToPathFront (Join-Path $qtHome 'bin')

    $qtVersion = (& (Join-Path $qtHome 'bin\qmake.exe') -query QT_VERSION 2>$null | Select-Object -First 1)
    Write-Ok ("Qt {0}: {1}" -f $qtVersion, $qtHome)
    return $true
}

function Resolve-Wix {
    $candidates = @()
    if ($WixDir)   { $candidates += $WixDir }
    if ($env:WIX)  { $candidates += $env:WIX }

    foreach ($programFiles in @(${env:ProgramFiles(x86)}, $env:ProgramFiles)) {
        if (-not $programFiles) { continue }
        $dirs = Get-ChildItem -LiteralPath $programFiles -Directory -ErrorAction SilentlyContinue |
                Where-Object { $_.Name -like 'WiX Toolset v3*' } |
                Sort-Object Name -Descending
        foreach ($d in $dirs) { $candidates += $d.FullName }
    }

    foreach ($candidate in $candidates) {
        if (-not $candidate) { continue }
        $trimmed = $candidate.TrimEnd('\')
        if (Test-Path -LiteralPath (Join-Path $trimmed 'bin\candle.exe')) {
            $env:WIX = $trimmed
            Add-ToPathFront (Join-Path $trimmed 'bin')
            Write-Ok "WiX Toolset v3: $trimmed"
            return $true
        }
    }

    Write-Fail 'WiX Toolset v3 not found (needed to build the .msi).'
    Write-Note 'Install it with:  choco install -y wixtoolset     (or pass -WixDir <path>)'
    return $false
}

function Get-UuidGenPath {
    $roots = @()
    foreach ($programFiles in @(${env:ProgramFiles(x86)}, $env:ProgramFiles)) {
        if ($programFiles) { $roots += (Join-Path $programFiles 'Windows Kits\10\bin') }
    }

    $found = @()
    foreach ($root in $roots) {
        if (-not (Test-Path -LiteralPath $root)) { continue }
        $found += Get-ChildItem -LiteralPath $root -Filter 'uuidgen.exe' -Recurse -File -ErrorAction SilentlyContinue |
                  Where-Object { $_.DirectoryName -like '*\x64' }
    }

    if (-not $found) { return $null }
    return ($found | Sort-Object FullName -Descending | Select-Object -First 1).FullName
}

function Test-CMakeVersion {
    $cmakeExe = Get-CommandPath 'cmake.exe'
    if (-not $cmakeExe) {
        Write-Fail 'cmake not found.  choco install -y cmake  (and add it to PATH)'
        return $false
    }
    $line = (& $cmakeExe --version 2>$null | Select-Object -First 1)
    $version = $null
    if ($line -match '(\d+)\.(\d+)\.(\d+)') {
        $version = [version]("{0}.{1}.{2}" -f $matches[1], $matches[2], $matches[3])
    }
    if ($version -and $version -lt $MinCMakeVersion) {
        Write-Fail ("cmake {0} is too old, {1}+ is required." -f $version, $MinCMakeVersion)
        return $false
    }
    Write-Ok ("cmake {0}: {1}" -f $version, $cmakeExe)
    return $true
}

function Install-Prerequisites {
    $choco = Get-CommandPath 'choco.exe'
    if (-not $choco) {
        Write-Fail 'Chocolatey (choco) is not installed, cannot use -InstallPrereqs.'
        Write-Note 'See https://chocolatey.org/install , then re-run with -InstallPrereqs.'
        return
    }

    $packages = @()
    if (-not (Get-CommandPath 'git.exe'))   { $packages += 'git' }
    if (-not (Get-CommandPath 'cmake.exe')) { $packages += 'cmake' }
    if (-not (Get-CommandPath 'ninja.exe')) { $packages += 'ninja' }
    if (-not (Get-CommandPath '7z.exe'))    { $packages += '7zip' }
    if (-not $env:WIX -and -not (Get-CommandPath 'candle.exe')) { $packages += 'wixtoolset' }

    if (-not $packages) {
        Write-Ok 'All Chocolatey-installable tools are already present.'
        return
    }

    Write-Info ("choco install -y {0}" -f ($packages -join ' '))
    & $choco install -y @packages
    if ($LASTEXITCODE -ne 0) {
        Write-Warn "choco install returned $LASTEXITCODE - check the output above."
    }

    # Refresh PATH from the registry so the freshly installed tools are visible now.
    $machinePath = [Environment]::GetEnvironmentVariable('Path', 'Machine')
    $userPath    = [Environment]::GetEnvironmentVariable('Path', 'User')
    $env:PATH    = "$machinePath;$userPath;$env:PATH"
}

function Test-Prerequisites {
    Write-Step 'Checking prerequisites and preparing the environment'

    if ($InstallPrereqs) { Install-Prerequisites }

    $ok = $true

    # --- basic tools -------------------------------------------------------
    foreach ($tool in @(
        @{ Name = 'git.exe';   Hint = 'choco install -y git' },
        @{ Name = 'ninja.exe'; Hint = 'choco install -y ninja' },
        @{ Name = 'curl.exe';  Hint = 'ships with Windows 10/11 and Git for Windows' }
    )) {
        $path = Get-CommandPath $tool.Name
        if ($path) { Write-Ok ("{0}: {1}" -f $tool.Name, $path) }
        else { Write-Fail ("{0} not found.  {1}" -f $tool.Name, $tool.Hint); $ok = $false }
    }

    if (-not (Test-CMakeVersion)) { $ok = $false }

    # --- 7-Zip (setup.bat and the 7z package type need it) -----------------
    $sevenZip = Get-CommandPath '7z.exe'
    if (-not $sevenZip) {
        foreach ($guess in @('C:\Program Files\7-Zip', 'C:\Program Files (x86)\7-Zip')) {
            if (Test-Path -LiteralPath (Join-Path $guess '7z.exe')) {
                Add-ToPathFront $guess
                $sevenZip = Join-Path $guess '7z.exe'
                break
            }
        }
    }
    if ($sevenZip) { Write-Ok "7-Zip: $sevenZip" }
    else { Write-Fail '7z not found.  choco install -y 7zip'; $ok = $false }

    # --- bash / Visual Studio / Qt ----------------------------------------
    if (-not (Resolve-Bash))          { $ok = $false }
    if (-not (Resolve-VisualStudio))  { $ok = $false }
    if (-not (Resolve-Qt))            { $ok = $false }

    # --- WiX (only for msi / portable packaging) ---------------------------
    $needsWix = (-not $BuildOnly) -and (-not $CheckOnly) -and ($Portable -or ($BuildMode -in @('stable', 'testing')))
    if ($needsWix) {
        if (-not (Resolve-Wix)) { $ok = $false }
    }
    elseif ($env:WIX) {
        Write-Info "WIX = $env:WIX"
    }

    # --- Jack headers (installed by setup.bat) -----------------------------
    if (Test-Path -LiteralPath $JackDir) {
        Add-ToPathFront $JackDir
        Write-Ok "Jack: $JackDir"
    }
    else {
        Write-Info "Jack not installed yet (setup.bat will place it in '$JackDir')."
    }

    # --- dependencies bundle ----------------------------------------------
    if (Test-Path -LiteralPath $DepsDir) { Write-Ok "Dependencies: $DepsDir" }
    else { Write-Info "Dependencies not downloaded yet (setup.bat will fill '$DepsDir')." }

    # --- uuidgen (package.bat hard-codes an SDK path) ----------------------
    $uuidgen = Get-UuidGenPath
    if ($uuidgen) { Write-Ok "uuidgen: $uuidgen" }
    else { Write-Info 'uuidgen.exe not found in the Windows SDK - PowerShell will generate the product GUID.' }

    # --- disk space --------------------------------------------------------
    try {
        $driveName = (Get-Item -LiteralPath $RepoRoot).PSDrive.Name
        $freeGb    = [math]::Round((Get-PSDrive -Name $driveName).Free / 1GB, 1)
        if ($freeGb -lt $MinFreeGb) {
            Write-Warn ("Only {0} GB free on {1}: - a full build needs about {2} GB." -f $freeGb, $driveName, $MinFreeGb)
        }
        else {
            Write-Ok ("Free disk space on {0}: {1} GB" -f $driveName, $freeGb)
        }
    }
    catch { Write-Info 'Could not determine free disk space.' }

    # --- long paths --------------------------------------------------------
    try {
        $longPaths = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' `
                        -Name 'LongPathsEnabled' -ErrorAction SilentlyContinue).LongPathsEnabled
        if ($longPaths -ne 1) {
            Write-Warn 'Win32 long paths are disabled. Deep Qt/CMake paths may break the build.'
            Write-Note 'Fix: Set-ItemProperty "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" LongPathsEnabled 1'
            $repoDepth = $RepoRoot.Length
            if ($repoDepth -gt 40) {
                Write-Warn ("The repository path is {0} characters long - consider moving it to C:\MuseScore." -f $repoDepth)
            }
        }
    }
    catch { }

    if (-not $ok) {
        throw 'Prerequisite check failed. Fix the [FAIL] items above and run the script again.'
    }

    Write-Ok 'All prerequisites satisfied.'
}

# ============================================================================
#  Pipeline steps
# ============================================================================

function Invoke-CleanStep {
    Write-Step 'Cleaning previous build output'
    foreach ($dir in @('build.release', 'build.install', 'build.artifacts', 'msvc.build', 'msvc.install')) {
        $full = Join-Path $RepoRoot $dir
        if (Test-Path -LiteralPath $full) {
            Write-Info "removing $dir"
            Remove-Item -LiteralPath $full -Recurse -Force -ErrorAction SilentlyContinue
        }
    }
    Write-Ok 'Clean done.'
}

function Invoke-SubmodulesStep {
    Write-Step 'Updating git submodules (muse_framework, muse_deps)'
    if ($SkipSubmodules) { Write-Info 'Skipped (-SkipSubmodules).'; return }

    Invoke-CmdScript -Title 'git submodule update' `
                     -CommandLine 'git submodule update --init --recursive'
    Write-Ok 'Submodules are up to date.'
}

function Invoke-DependenciesStep {
    Write-Step 'Downloading Windows dependencies (setup.bat)'

    if ($SkipDeps) { Write-Info 'Skipped (-SkipDeps).'; return }

    if ((Test-Path -LiteralPath $DepsDir) -and (Test-Path -LiteralPath $JackDir)) {
        Write-Info "Dependencies already present in '$DepsDir'."
        if (-not (Confirm-Continue 'Download them again?')) {
            Write-Ok 'Using the existing dependencies.'
            return
        }
    }

    $portableArg = if ($Portable) { ' --portable ON' } else { '' }
    Invoke-CmdScript -Title 'setup.bat' -CommandLine ('{0}{1}' -f $SetupBat, $portableArg)

    if (-not (Test-Path -LiteralPath $DepsDir)) {
        throw "setup.bat finished but '$DepsDir' does not exist. Check your internet connection / proxy."
    }
    Add-ToPathFront $JackDir
    Write-Ok 'Dependencies installed.'
}

function Resolve-BuildNumber {
    if ($BuildNumber) {
        if ($BuildNumber -notmatch '^\d+$') {
            throw "BuildNumber must be numeric, got '$BuildNumber'."
        }
        if ($BuildNumber.Length -gt 9) {
            throw "BuildNumber must be at most 9 digits (WiX stores it in an Int32), got '$BuildNumber'."
        }
        return $BuildNumber
    }
    # Same rule as buildscripts/ci/tools/make_build_number.sh
    return ((Get-Date).ToUniversalTime().ToString('yyMMddHHmm')).Substring(0, 9)
}

function Invoke-MetadataStep {
    param([string] $Number)

    Write-Step 'Generating build metadata (build_mode.env / build_number.env)'

    New-Item -ItemType Directory -Path $EnvDir -Force | Out-Null

    Invoke-BashScript -Title 'make_build_mode_env.sh' -Arguments @(
        './buildscripts/ci/tools/make_build_mode_env.sh', '-e', 'workflow_dispatch', '-m', $BuildMode)

    Invoke-BashScript -Title 'make_build_number.sh' -Arguments @(
        './buildscripts/ci/tools/make_build_number.sh', $Number)

    foreach ($file in @('build_mode.env', 'build_number.env')) {
        $full = Join-Path $EnvDir $file
        if (-not (Test-Path -LiteralPath $full)) {
            throw "$file was not created. Is bash (Git Bash) working correctly?"
        }
        $value = Get-EnvFileValue -Path $full
        if (-not $value) { throw "$file is empty." }
        Write-Ok ("{0} = {1}" -f $file, $value)
    }
}

function Invoke-BuildStep {
    param([string] $Number)

    Write-Step 'Building MuseScore Studio (RelWithDebInfo + install)'
    Write-Info 'This is the long part: expect 2-4+ hours for a first build.'

    $portableArg = if ($Portable) { ' --portable ON' } else { '' }
    $commandLine = '{0} -n {1} --dockwidgets_v2 {2}{3}' -f $BuildBat, $Number, $DockWidgetsV2, $portableArg

    Invoke-CmdScript -Title 'build.bat' -CommandLine $commandLine

    $exeName = 'MuseScoreStudio5.exe'
    $exePath = if ($Portable) {
        Join-Path $InstallDir ('App\MuseScore\bin\{0}' -f $exeName)
    } else {
        Join-Path $InstallDir ('bin\{0}' -f $exeName)
    }

    if (-not (Test-Path -LiteralPath $BuildDir)) {
        throw "build.release was not created - the build failed. See the log above."
    }
    if (-not (Test-Path -LiteralPath $exePath)) {
        Write-Warn "Expected executable not found at: $exePath"
        Write-Warn 'The packaging step will probably fail. Check the build log for errors.'
    }
    else {
        Write-Ok "Built: $exePath"
    }
}

function New-PatchedPackageScript {
    <#
        package.bat hard-codes
            SET UUIDGEN="C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x64\uuidgen.exe"
        which does not exist on most machines. Instead of editing the repository file
        we write a patched copy into build.artifacts (git-ignored) and run that.
        Returns a path relative to the repository root (so it never contains spaces).
    #>
    $originalPath = Join-Path $RepoRoot $PackageBat
    $content      = Get-Content -LiteralPath $originalPath -Raw
    $uuidgen      = Get-UuidGenPath

    if ($uuidgen -and $content.Contains($uuidgen)) {
        Write-Info "Using uuidgen: $uuidgen (package.bat already points at it)"
        return $PackageBat
    }

    if ($uuidgen) {
        $uuidgenLine = 'SET UUIDGEN="' + $uuidgen + '"'
        $productGuid = $null
        Write-Info "Using uuidgen: $uuidgen"
    }
    else {
        $uuidgenLine = 'REM UUIDGEN not available, GUID generated by build_setup_x64.ps1'
        $productGuid = [guid]::NewGuid().ToString().ToUpperInvariant()
        Write-Info 'No uuidgen.exe found in the Windows SDK - generating the product GUID with PowerShell.'
        Write-Info "Product GUID: $productGuid"
    }

    $patchedLines = New-Object System.Collections.Generic.List[string]
    $replacedUuidGen = $false
    $replacedCall    = $false

    foreach ($line in ($content -split "`r?`n")) {
        if ($line -match '^\s*SET UUIDGEN=') {
            $patchedLines.Add($uuidgenLine) | Out-Null
            $replacedUuidGen = $true
        }
        elseif ($productGuid -and ($line -match '^\s*%UUIDGEN%\s*>\s*uuid\.txt\s*$')) {
            # No trailing space before '>' or SET /p would read the space as well.
            $patchedLines.Add(('ECHO {0}> uuid.txt' -f $productGuid)) | Out-Null
            $replacedCall = $true
        }
        else {
            $patchedLines.Add($line) | Out-Null
        }
    }

    if (-not $replacedUuidGen) {
        Write-Warn 'Could not find the "SET UUIDGEN=" line in package.bat - using the original script.'
        return $PackageBat
    }
    if ($productGuid -and -not $replacedCall) {
        Write-Warn 'Could not find the uuidgen call in package.bat - using the original script.'
        return $PackageBat
    }

    New-Item -ItemType Directory -Path $ArtifactsDir -Force | Out-Null
    $relativePath = 'build.artifacts\package_x64.generated.bat'
    $patchedPath  = Join-Path $RepoRoot $relativePath
    Set-Content -LiteralPath $patchedPath -Value ($patchedLines -join "`r`n") -Encoding ASCII
    Write-Info "Patched package script: $relativePath"
    return $relativePath
}

function Confirm-PackageEnvFiles {
    param([string] $Number)

    # build.bat normally creates these; regenerate them for -PackageOnly runs.
    $required = @{
        'build_mode.env'     = @('./buildscripts/ci/tools/make_build_mode_env.sh', '-e', 'workflow_dispatch', '-m', $BuildMode)
        'build_number.env'   = @('./buildscripts/ci/tools/make_build_number.sh', $Number)
        'build_revision.env' = @('./buildscripts/ci/tools/make_revision_env.sh')
        'build_version.env'  = @('./buildscripts/ci/tools/make_version_env.sh', $Number)
        'build_branch.env'   = @('./buildscripts/ci/tools/make_branch_env.sh')
    }

    New-Item -ItemType Directory -Path $EnvDir -Force | Out-Null

    foreach ($file in @($required.Keys)) {
        $full  = Join-Path $EnvDir $file
        $value = Get-EnvFileValue -Path $full
        if (-not $value) {
            Write-Info "$file missing or empty - regenerating"
            Invoke-BashScript -Title ("regenerate {0}" -f $file) -Arguments $required[$file]
        }
    }

    foreach ($file in @($required.Keys)) {
        $full  = Join-Path $EnvDir $file
        $value = Get-EnvFileValue -Path $full
        if (-not $value) {
            throw "build.artifacts\env\$file is missing or empty - see docs/windows-build-troubleshooting.md"
        }
        Write-Ok ("{0} = {1}" -f $file, $value)
    }
}

function Invoke-PackageStep {
    param([string] $Number)

    Write-Step 'Creating the installer (package.bat)'

    if (-not (Test-Path -LiteralPath $BuildDir)) {
        throw @"
build.release does not exist, so packaging cannot run.
Run the build first:
    .\build_setup_x64.ps1 -BuildMode $BuildMode
(see docs/windows-build-troubleshooting.md, section 1: "CMake Error: The source directory ...")
"@
    }
    if (-not (Test-Path -LiteralPath (Join-Path $BuildDir 'CMakeCache.txt'))) {
        throw "build.release exists but is not configured (no CMakeCache.txt). Re-run the build step."
    }
    if (-not (Test-Path -LiteralPath $InstallDir)) {
        throw "build.install does not exist. Run the build step before packaging."
    }

    Confirm-PackageEnvFiles -Number $Number

    $packageScript = New-PatchedPackageScript
    $portableArg   = if ($Portable) { ' --portable ON' } else { '' }
    $commandLine   = '{0} -m {1} --guid {2}{3}' -f $packageScript, $BuildMode, $UpgradeGuid, $portableArg

    Invoke-CmdScript -Title 'package.bat' -CommandLine $commandLine
    Write-Ok 'Packaging finished.'
}

function Invoke-ChecksumStep {
    Write-Step 'Creating the checksum'
    $artifactNameFile = Join-Path $EnvDir 'artifact_name.env'
    if (-not (Test-Path -LiteralPath $artifactNameFile)) {
        Write-Warn 'artifact_name.env not found - skipping the checksum.'
        return
    }
    Invoke-BashScript -Title 'checksum.sh' -AllowFailure `
                      -Arguments @('./buildscripts/ci/tools/checksum.sh')

    $checksumFile = Join-Path $ArtifactsDir 'checksum.txt'
    if (Test-Path -LiteralPath $checksumFile) {
        Write-Ok "checksum: $checksumFile"
        Get-Content -LiteralPath $checksumFile | ForEach-Object { Write-Note $_ }
    }
}

function Write-Summary {
    $elapsed = (Get-Date) - $script:StartTime

    Write-Host ''
    Write-Host ('=' * 78) -ForegroundColor DarkGreen
    Write-Host '  SUMMARY' -ForegroundColor Green
    Write-Host ('=' * 78) -ForegroundColor DarkGreen

    Write-Host ("  Build mode : {0}{1}" -f $BuildMode, $(if ($Portable) { ' (PortableApps)' } else { '' }))
    Write-Host ("  Elapsed    : {0:hh\:mm\:ss}" -f $elapsed)

    if (Test-Path -LiteralPath $ArtifactsDir) {
        $artifacts = Get-ChildItem -LiteralPath $ArtifactsDir -File -ErrorAction SilentlyContinue |
                     Where-Object { $_.Extension -in @('.msi', '.exe', '.7z') } |
                     Sort-Object LastWriteTime -Descending
        if ($artifacts) {
            Write-Host '  Artifacts  :' -ForegroundColor Green
            foreach ($artifact in $artifacts) {
                Write-Host ("    {0}  ({1:N1} MB)" -f $artifact.FullName, ($artifact.Length / 1MB)) -ForegroundColor Green
            }
        }
        else {
            Write-Host "  Artifacts  : none found in $ArtifactsDir" -ForegroundColor Yellow
        }
    }

    $exePath = if ($Portable) {
        Join-Path $InstallDir 'App\MuseScore\bin\MuseScoreStudio5.exe'
    } else {
        Join-Path $InstallDir 'bin\MuseScoreStudio5.exe'
    }
    if (Test-Path -LiteralPath $exePath) {
        Write-Host "  Executable : $exePath"
    }

    if ($script:Warnings.Count -gt 0) {
        Write-Host ''
        Write-Host ("  {0} warning(s):" -f $script:Warnings.Count) -ForegroundColor Yellow
        foreach ($warning in $script:Warnings) { Write-Host "    - $warning" -ForegroundColor Yellow }
    }

    Write-Host ''
    Write-Host '  Unsigned installers are normal here; Windows SmartScreen may show' -ForegroundColor DarkGray
    Write-Host '  an "unknown publisher" warning when you run them.' -ForegroundColor DarkGray
    Write-Host ''
}

function Write-FailureHelp {
    param([string] $Message)

    Write-Host ''
    Write-Host ('=' * 78) -ForegroundColor DarkRed
    Write-Host '  BUILD FAILED' -ForegroundColor Red
    Write-Host ('=' * 78) -ForegroundColor DarkRed
    Write-Host "  $Message" -ForegroundColor Red
    Write-Host ''
    Write-Host '  Troubleshooting:' -ForegroundColor Yellow
    Write-Host '    * docs/windows-build-troubleshooting.md  - known errors and fixes'
    Write-Host '    * docs/local-windows-x64-setup.md        - full setup guide (Persian)'
    Write-Host '    * "WSL ERROR: execvpe(/bin/bash) failed" -> install Git for Windows (Git Bash)'
    Write-Host '    * "The system cannot find the path specified" while reading *.env'
    Write-Host '      -> re-run without -PackageOnly so build.bat regenerates the env files'
    Write-Host '    * "CMake Error: The source directory ... does not contain CMakeLists.txt"'
    Write-Host '      -> build.release is missing/broken; run a full build (add -Clean)'
    Write-Host '    * Re-run just the check with:  .\build_setup_x64.ps1 -CheckOnly'
    Write-Host ''
}

# ============================================================================
#  Main
# ============================================================================

if (-not (Test-Path -LiteralPath (Join-Path $RepoRoot 'CMakeLists.txt'))) {
    Write-Host "[FAIL] CMakeLists.txt not found in $RepoRoot" -ForegroundColor Red
    Write-Host '       Run this script from the root of the MuseScore repository.' -ForegroundColor Red
    exit 1
}

if (-not (Test-Administrator)) {
    if ($NoElevate) {
        Write-Host '[FAIL] Administrator rights are required (-NoElevate was given).' -ForegroundColor Red
        exit 1
    }
    Invoke-SelfElevation -BoundParameters $PSBoundParameters
    exit 0
}

Set-Location -LiteralPath $RepoRoot

Write-Host ''
Write-Host '################################################################################' -ForegroundColor Magenta
Write-Host '#   MuseScore Studio / Persian Tuner  -  Windows x64 setup builder             #' -ForegroundColor Magenta
Write-Host '#   docs/local-windows-x64-setup.md  +  docs/windows-build-troubleshooting.md  #' -ForegroundColor Magenta
Write-Host '################################################################################' -ForegroundColor Magenta
Write-Host ("  Repository : {0}" -f $RepoRoot)
try {
    Write-Host ("  Branch     : {0}" -f (& git rev-parse --abbrev-ref HEAD 2>$null))
    Write-Host ("  Commit     : {0}" -f (& git rev-parse --short=7 HEAD 2>$null))
}
catch {
    Write-Host '  Branch     : (git not available yet)'
}
Write-Host ("  Build mode : {0}{1}" -f $BuildMode, $(if ($Portable) { ' (PortableApps .paf.exe)' } else { '' }))
Write-Host ("  Started    : {0}" -f $script:StartTime.ToString('yyyy-MM-dd HH:mm:ss'))

$transcriptStarted = $false
try {
    New-Item -ItemType Directory -Path (Join-Path $ArtifactsDir 'logs') -Force | Out-Null
    $logPath = Join-Path $ArtifactsDir ('logs\build_setup_x64_{0}.log' -f (Get-Date -Format 'yyyyMMdd_HHmmss'))
    Start-Transcript -Path $logPath -Force | Out-Null
    $transcriptStarted = $true
    Write-Host ("  Log file   : {0}" -f $logPath)
}
catch {
    Write-Host '  [info] Could not start a transcript log (continuing without it).' -ForegroundColor Gray
}

$exitCode = 0
try {
    Test-Prerequisites

    if ($CheckOnly) {
        Write-Host ''
        Write-Ok 'Check finished - this machine is ready to build the x64 setup.'
        Write-Host ''
        Write-Host '  Next:  .\build_setup_x64.ps1 -BuildMode stable' -ForegroundColor Cyan
    }
    else {
        $resolvedNumber = Resolve-BuildNumber
        Write-Info "Build number: $resolvedNumber"

        if ($Clean) {
            if ($PackageOnly) {
                Write-Warn '-Clean is ignored together with -PackageOnly (it would delete the build you want to package).'
            }
            else {
                Invoke-CleanStep
            }
        }

        if (-not $PackageOnly) {
            Invoke-SubmodulesStep
            Invoke-DependenciesStep
            Invoke-MetadataStep -Number $resolvedNumber
            Invoke-BuildStep    -Number $resolvedNumber
        }
        else {
            Write-Info 'Skipping submodules/dependencies/build (-PackageOnly).'
        }

        if (-not $BuildOnly) {
            Invoke-PackageStep -Number $resolvedNumber
            Invoke-ChecksumStep
        }
        else {
            Write-Info 'Skipping packaging (-BuildOnly).'
        }

        Write-Summary
    }
}
catch {
    Write-FailureHelp -Message $_.Exception.Message
    if ($_.ScriptStackTrace) { Write-Verbose $_.ScriptStackTrace }
    $exitCode = 1
}
finally {
    if ($transcriptStarted) {
        try { Stop-Transcript | Out-Null } catch { }
    }
}

exit $exitCode
